### ISSUE TITLE
F5. Post quiz answers for one monument

### ISSUE THREAD

**Issue by JCastanho** [JCastanho/CMUProj#5]

**Comment by Danisodu** [comment]
Depois de respondidas todas as perguntas, deve haver, no menu principal onde se vêm as localizaç
ões, uma especie de icon que identifique que o quizz foi respondido (tipo messenger).
Se o utilizador acabar a sua tour na localização relacionada com o quizz que está a submeter as respostas, ele tem que indicar isso (pensar como implementar isto e para queq vai servir)

**Depois de wifi direct estar implementado, garantir que:**

- Quizzes must be answered between two stops on the tour: the stop  where  the  quiz  was  obtained  and  to  which  the  questions  are  related,  and  the  following  stop.
